# Adapter configurations for ORBIT
# This file contains all adapter definitions and can be imported by config.yaml

adapters:
  - name: "qa-sql"
    type: "retriever"
    datasource: "sqlite"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QASSQLRetriever"
    config:
      # QA-specific settings
      confidence_threshold: 0.3
      max_results: 5
      return_results: 3
      
      # Adapter granularity strategy settings
      query_timeout: 5000
      enable_query_monitoring: true
      
      # Security and access control (recommended)
      table: "city"  # Specify the exact table for single-table access
      allowed_columns: ["id", "question", "answer", "category", "confidence"]  # Limit accessible columns
      security_filter: "active = 1"  # Only return active Q&A pairs
      
      # Performance optimization
      cache_ttl: 1800  # Cache results for 30 minutes
      
    # Fault tolerance settings for this adapter
    fault_tolerance:
      operation_timeout: 15.0          # Lower timeout for local database operations
      failure_threshold: 10            # Higher threshold for local operations (more reliable)
      enable_thread_isolation: false   # No isolation needed for local SQLite operations
      enable_process_isolation: false  # SQLite is lightweight, no process isolation needed
      max_retries: 3                   # Retry failed queries
      retry_delay: 0.5                 # Short delay between retries for local DB
      
  - name: "qa-vector-chroma"
    type: "retriever"
    datasource: "chroma"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QAChromaRetriever"
    config:
      collection: "city"
      confidence_threshold: 0.3
      distance_scaling_factor: 200.0
      embedding_provider: null
      max_results: 5
      return_results: 3
      
    # Fault tolerance settings for this adapter
    fault_tolerance:
      operation_timeout: 25.0          # Longer timeout for network operations
      failure_threshold: 3             # Lower threshold for external service
      enable_thread_isolation: true    # Use thread isolation for network operations
      enable_process_isolation: false  # Thread isolation sufficient for most cases
      max_retries: 2                   # Fewer retries for network operations
      retry_delay: 1.0                 # Longer delay between retries
      
  - name: "qa-vector-qdrant"
    type: "retriever"
    datasource: "qdrant"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QAQdrantRetriever"
    config:
      collection: "city"
      confidence_threshold: 0.3
      score_scaling_factor: 200.0
      embedding_provider: null
      max_results: 5
      return_results: 3
      
    # Fault tolerance settings for this adapter
    fault_tolerance:
      operation_timeout: 10.0          # Reduced timeout for faster failure detection
      failure_threshold: 2             # Lower threshold for external service
      enable_thread_isolation: true    # Use thread isolation for network operations
      enable_process_isolation: false  # Thread isolation sufficient
      max_retries: 1                   # Fewer retries for network operations
      retry_delay: 1.0                 # Shorter delay for Qdrant
      
  - name: "file-vector"
    type: "retriever"
    datasource: "chroma"
    adapter: "file"
    implementation: "retrievers.implementations.file.FileChromaRetriever"
    config:
      confidence_threshold: 0.1
      distance_scaling_factor: 150.0
      embedding_provider: null
      max_results: 10
      return_results: 5
      # File-specific settings
      include_file_metadata: true
      boost_file_uploads: true
      file_content_weight: 1.5
      metadata_weight: 0.8
      
    # Fault tolerance settings for this adapter
    fault_tolerance:
      operation_timeout: 35.0          # Longer timeout for file operations (larger datasets)
      failure_threshold: 5             # More tolerance for file operations
      enable_thread_isolation: true    # Use thread isolation for file processing
      enable_process_isolation: false  # Thread isolation sufficient for file operations
      max_retries: 3                   # More retries for file operations
      retry_delay: 2.0                 # Longer delay for file operations
